### ISSUE TITLE
Queries about development

### ISSUE THREAD

**Issue by Npidys** [ckflight/ESC_BLDC_HARDWARE#3]
I have a few queries about developing an ESC similar to this, as a part of a student project:

1. What was the battery voltage when you tested this ESC at 40A? Is it limited to 3S/4S ?
2. The MP1907 drivers are currently out of stock. Can they be replaced with MP1907A, in your opinion? The electrical quantities look mostly the same to me. https://www.monolithicpower.com/en/mp1907a.html - MP1907A

Thanks!

**Comment by ckflight** [comment]
Hi,
1. It is tested with both 4s and 6s. Check the maximum ratings which is clarified here: https://github.com/ckflight/ESC_BLDC_HARDWARE/issues/1

2. Yes it looks exactly the same. 

You are welcome. Regards.
