### ISSUE TITLE
The speed is not increasing.

### ISSUE THREAD

**Issue by ghost** [ckflight/ESC_BLDC_HARDWARE#4]
C_H_30 and C_H_50 blheli_s firmware were installed in a 4s battery environment.
Even if the PWM input duty is raised, the EFM IC controls it only at a constant low speed. What should we look at?

**Comment by ckflight** [comment]
Is it properly spinning at low speed can you upload a video to show. If it is rotating properly even if at the low speed then this is an indication of a working esc but it is not responding to the pwm command. 

1. Check pwm frequency it should be oneshot 125 (125us – 250us), 42 or multishot etc. Google for blheli_s pwm protocols and its timings. Therefore check pwm signal and its timing with a scope as well.
2. Check if the esc's mcu gets the pwm signal and it is assigned to the correct pin.

Regards.
