### ISSUE TITLE
ESC goes into calibration mode every time.

### ISSUE THREAD

**Issue by maniksingla2166** [ckflight/ESC_BLDC_HARDWARE#6]
Hiii,
we have some success in uploading the firmware but when i power the ESC and increasing the RC Stick it went to into calibration mode repetitive and motor is not spinning at all. Any help will be appreciated.

**Comment by ckflight** [comment]
If it goes into the calibration mode then your rc is not calibrated. It send higher throttle command than the idle value. Try to increase idle value and test again. Also are you using my own design.

For testing increase PPM Min Throttle value on BLHeli Suite settings. Also check what is the lowest value your RC Throttle sends.

**Comment by maniksingla2166** [comment]
Hi, sorry for the late reply , had my exams in between . Thanks for all the help , got it working , there were some minor issues in assembling the pcb .
